version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=demo_db
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db