"""First migrations

Revision ID: 4b4def07695d
Revises: None
Create Date: 2022-06-16 23:14:13.634518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum

# revision identifiers, used by Alembic.

revision = '4b4def07695d'
down_revision = None
branch_labels = None
depends_on = None

ShopUnitType = Enum('offer', 'category', name='shop_unit_type')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', ShopUnitType, nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__nodes'))
    )
    op.create_table('nodes_children',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('children_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['nodes.id'], name=op.f('fk__nodes_children__children_id__nodes')),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk__nodes_children__node_id__nodes')),
    sa.PrimaryKeyConstraint('node_id', name=op.f('pk__nodes_children'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes_children')
    op.drop_table('nodes')
    # ### end Alembic commands ###
    ShopUnitType.drop(op.get_bind())
