"""Migrations

Revision ID: 5772a0fc0104
Revises: 
Create Date: 2022-06-18 19:12:49.203422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5772a0fc0104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('offer', 'category', name='shop_unit_type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__nodes'))
    )
    op.create_table('nodes_children',
    sa.Column('children_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['nodes.id'], name=op.f('fk__nodes_children__children_id__nodes')),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk__nodes_children__node_id__nodes')),
    sa.PrimaryKeyConstraint('children_id', name=op.f('pk__nodes_children'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes_children')
    op.drop_table('nodes')
    # ### end Alembic commands ###
