"""Migrations

Revision ID: b2fe7093de13
Revises: 
Create Date: 2022-06-19 16:27:11.402653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2fe7093de13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__imports'))
    )
    op.create_table('nodes',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('offer', 'category', name='shopunittype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__nodes'))
    )
    op.create_table('relates',
    sa.Column('children_id', postgresql.UUID(), nullable=False),
    sa.Column('node_id', postgresql.UUID(), nullable=True),
    sa.Column('import_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['children_id'], ['nodes.id'], name=op.f('fk__relates__children_id__nodes')),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk__relates__import_id__imports')),
    sa.PrimaryKeyConstraint('children_id', name=op.f('pk__relates'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relates')
    op.drop_table('nodes')
    op.drop_table('imports')
    # ### end Alembic commands ###
